# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GuQpweqrKLXGX-0zLkC7qmsd98gZCna
"""

# Install required packages
!pip install alibi-detect
!pip install matplotlib
!pip install pandas
!pip install scikit-learn

# Import libraries
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from alibi_detect.cd import KSDrift
import matplotlib.pyplot as plt

# Load the dataset

df = pd.read_csv('Country-data.csv')

# Select relevant numeric features for clustering
# Adjust this based on the characteristics of your dataset
X_train = df.iloc[:, 1:].values

# Train KMeans model
kmeans = KMeans(n_clusters=3, random_state=0)
kmeans.fit(X_train)

# Simulate data drift (you may need to customize this based on your dataset)
X_drift = X_train + np.random.normal(0, 3, size=X_train.shape)

# Initialize drift detector
detector = KSDrift(X_train, p_val=.05)

# Detect drift
preds_drift = detector.predict(X_drift)

# Visualize the data
plt.scatter(X_train[:, 0], X_train[:, 1], label='Initial Data', alpha=0.7)
plt.scatter(X_drift[:, 0], X_drift[:, 1], label='Data with Drift', alpha=0.7)
plt.title('Data Drift Visualization')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.show()